### ISSUE TITLE
ask for releasing on jade

### ISSUE THREAD

**Issue by k-okada** [pr2-gbp/pr2_controllers-release#1]
Hi,

some of our program depends on pr2_controllers_msgs so could you release them into jade distribution?
I think

```
 bloom-release pr2_controllers -y --track jade --rosdistro jade
```

may work

Thanks in advance.

**Comment by UltronDestroyer** [comment]
Of course. Will do that right now.

**Comment by UltronDestroyer** [comment]
It's blocked at the moment by pr2_mechanism_msgs, I'm releasing that and then will get back.

**Comment by UltronDestroyer** [comment]
Waiting on pr2_mechanism now

**Comment by UltronDestroyer** [comment]
Ended up blocked by ros_controls

```
Could not resolve rosdep key 'controller_interface'
Failed to resolve controller_interface on ubuntu:trusty with: Error running generator: Failed to resolve     rosdep key 'controller_interface', aborting.
controller_interface is depended on by these packages: ['pr2_controller_interface']
```

**Comment by k-okada** [comment]
https://github.com/ros-gbp/ros_control-release/issues/1
asked for release

**Comment by UltronDestroyer** [comment]
Pending release on pr2_mechanism https://github.com/ros/rosdistro/pull/9915

**Comment by UltronDestroyer** [comment]
Released https://github.com/ros/rosdistro/pull/9916#event-479309902

**Comment by k-okada** [comment]
thank you !!!! :sushi: :sushi: :sushi:
